# Site settings
title: eoe 上海同城会
email: shanghai@eoe.cn
description: "eoe 第一个线下官方同城会 - 上海同城会"
baseurl: ""
url: "http://shanghai.eoe.cn"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

# Account
username: eoeshanghai
